### ISSUE TITLE
hoodie start not working on new installations on Windows 8.1 x64

### ISSUE THREAD

**Issue by jammy-git** [hoodiehq/my-first-hoodie#71]
Installed node.js, github for windows and CouchDB last night, followed by hoodie-cli.

Created a new app and came across the following error when starting hoodie:
Initializing...
CouchDB started: http://127.0.0.1:6009
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

Stopping CouchDB...

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\nodejs\app\data\couch.pid'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at MultiCouch.stop (C:\nodejs\app\node_modules\hoodie-server\node_modules\mu
lticouch\lib\multicouch.js:114:23)
    at Object.exports.stop (C:\nodejs\app\node_modules\hoodie-server\lib\couchdb
\index.js:181:11)
    at process.<anonymous> (C:\nodejs\app\node_modules\hoodie-server\lib\couchdb
\index.js:76:13)
    at process.emit (events.js:95:17)
    at process.exit (node.js:711:17)
    at Domain.<anonymous> (C:\nodejs\app\node_modules\hoodie-server\lib\index.js
:64:13)
    at Domain.emit (events.js:95:17)
    at ChildProcess.emit (events.js:70:21)

Originally I had installed nodejs and CouchDB in Program Files, so after a lot of searching I found the issue with spaces in directories. Stupid issue but heyho, I uninstalled nodejs and Couchdb and installed them in their own folders as you can see from the error message.

Still got the same problem when starting hoodie. So after more searching I found the issue regarding set environment variables COUCH_BIN and COUCH_DEFAULT_INI, so I added those to my system, restarted, no difference. Even added the environment variable for win_bin - again no difference.

No matter what changes I make it seems hoodie is incapable of starting a couchdb instance?

**Comment by timurgepard** [comment]
Install x86 version. It works well

**Comment by gr2m** [comment]
@timurgepard thanks for the update! Make sure to check out the new hoodie we are working on, we will deprecate the old one soon. Get started at: https://github.com/hoodiehq/hoodie

**Comment by timurgepard** [comment]
@gr2m thank you for replying me! You have uncorrect path to erl.exe and to other stuff in new version.
